name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Fix safe.directory
        run: |
          git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: "gh-pages"
          folder: "build/web"
